name: DevOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use your local machine as the runner
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build and Load Docker Image
      run: |
        # Build locally and load directly into Minikube to skip pushing to DockerHub
        docker build -t flask-dashboard:latest .
        minikube image load flask-dashboard:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s-deploy.yaml
        kubectl apply -f ingress.yaml
        # Force a rollout to pull the new 'latest' image
        kubectl rollout restart deployment flask-app

    - name: Automate URL Access & DNS
      run: |
        # Automated script to ensure host mapping is correct
        chmod +x automate_access.sh
        ./automate_access.sh
